spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: website-1
            uri: http://localhost:8080/
            predicates:
              - Path=/api/website-1/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Authorization

          - id: website-2
            uri: http://localhost:8081/
            predicates:
              - Path=/api/website-2/**
            filters:
              - StripPrefix=1
              - RemoveRequestHeader=Authorization

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  kafka:
    #bootstrap-servers: localhost:9092
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    consumer:
      group-id: notifications-email-consumer-group
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.cloud.gateway.mvc: DEBUG
